//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sb49.Weather.Properties {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sb49.Weather.Properties.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E.
        /// </summary>
        public static string E {
            get {
                return ResourceManager.GetString("E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENE.
        /// </summary>
        public static string Ene {
            get {
                return ResourceManager.GetString("Ene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESE.
        /// </summary>
        public static string Ese {
            get {
                return ResourceManager.GetString("Ese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exceeded the number of requests to weather provider..
        /// </summary>
        public static string ExceededWeatherServerRequestCounts {
            get {
                return ResourceManager.GetString("ExceededWeatherServerRequestCounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N.
        /// </summary>
        public static string N {
            get {
                return ResourceManager.GetString("N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NE.
        /// </summary>
        public static string Ne {
            get {
                return ResourceManager.GetString("Ne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NNE.
        /// </summary>
        public static string Nne {
            get {
                return ResourceManager.GetString("Nne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NNW.
        /// </summary>
        public static string Nnw {
            get {
                return ResourceManager.GetString("Nnw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NW.
        /// </summary>
        public static string Nw {
            get {
                return ResourceManager.GetString("Nw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.
        /// </summary>
        public static string S {
            get {
                return ResourceManager.GetString("S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SE.
        /// </summary>
        public static string Se {
            get {
                return ResourceManager.GetString("Se", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSE.
        /// </summary>
        public static string Sse {
            get {
                return ResourceManager.GetString("Sse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSW.
        /// </summary>
        public static string Ssw {
            get {
                return ResourceManager.GetString("Ssw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SW.
        /// </summary>
        public static string Sw {
            get {
                return ResourceManager.GetString("Sw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather provider API key is undefined..
        /// </summary>
        public static string UndefinedWeatherProviderApiKey {
            get {
                return ResourceManager.GetString("UndefinedWeatherProviderApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W.
        /// </summary>
        public static string W {
            get {
                return ResourceManager.GetString("W", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WNW.
        /// </summary>
        public static string Wnw {
            get {
                return ResourceManager.GetString("Wnw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WSW.
        /// </summary>
        public static string Wsw {
            get {
                return ResourceManager.GetString("Wsw", resourceCulture);
            }
        }
    }
}
